export const PLANT_AVATARS = [
  { id: 'monstera',  url: '/avatar/plants/monstera.png',  label: 'Monstera' },
  { id: 'pothos',    url: '/avatar/plants/pothos.png',    label: 'Pothos' },
  { id: 'cactusLargo',   url: '/avatar/plants/cactusLargo.png',    label: 'Cactus Largo' },
  { id: 'cactusRedondo',   url: '/avatar/plants/cactusRedondo.png',    label: 'Cactus' },
  { id: 'orquidea', url: '/avatar/plants/orquidea.png',  label: 'Orquídea' },
  { id: 'ficusGrande',    url: '/avatar/plants/ficusGrande.png',     label: 'Ficus' },
  { id: 'aloeVera',     url: '/avatar/plants/aloeVera.png',      label: 'Aloe Vera' },
  { id: 'aveParaiso',     url: '/avatar/plants/aveParaiso.png',      label: 'Ave Paraíso' },
  { id: 'begoniaMaculata',     url: '/avatar/plants/begoniaMaculata.png',      label: 'Begonia Maculata' },
  { id: 'bonsaiUno',     url: '/avatar/plants/bonsaiUno.png',      label: 'Bonsai Verde' },
  { id: 'bonsaiDos',     url: '/avatar/plants/bonsaiDos.png',      label: 'Bonsai Rojo' },
  { id: 'cunaMoises',     url: '/avatar/plants/cunaMoises.png',      label: 'Cuna de Moisés' },
  { id: 'lenguaSuegra',     url: '/avatar/plants/lenguaSuegra.png',      label: 'Lengua de Suegra' },
];